name: RandomItemChallenge
version: @version@
main: com.elementars.randomitemchallenge.RandomItemChallenge
api-version: 1.16
authors: [Elementars]
description: Random item challenge from Dream
commands:
  ric:
    description: Start/Stop RIC plugin
    usage: /<command> [start/stop]